+ rename: display what we tried to do if rename failed
so we can see src and dst arguments clearly.  we can't rely on the
output from 'mv' itself because we are not using "mv -v"

actually using '-v' might not be a bad idea, have to think about that...

diff --git a/rename b/rename
--- a/rename
+++ b/rename
@@ -46,5 +46,7 @@ do
 	elif [[ $from == '' || $append ]]; then newname="$file$to"
 	else newname="${file/$from/$to}"
 	fi
-	mv "$file" "$newname"
+
+	if ! mv "$file" "$newname"
+	then echo "failed to mv '$file' '$newname'"; false; fi
 done
